page_token: "EAAFRtinCqYcBAE3SHnp3ap759sLAUVrkVcJ7SAyEhKlFEtZAcZCjSZCvtU2fYSVoHP3ODFJZBw0pFLhDN66uJcObECGdRIlayhy54FUZCOsEOoCgtbrzdN592cRThfvjulzoEIEMGssTpdDyZC4qe6C2C39atG0cPxts9BWC8mgQZDZD"
database:
  adapter: 'mysql2' # or 'postgresql' or 'sqlite3'
  host: 'localhost'
  database: 'thebridge_development'
  username: 'root'
  password: ''
