page_token: "EAAPsXXTUUuwBALkVlTZBMOjYOyZC9yBqXHkTkqSavszti58FGJCTnKjQMe5kc6YfclULZAqJxZBv9OxJUsQNbL3xpgqKv03kcxVUoL3lIEZBaQiMZBrRvJlAhCACGoeTmAZAmLKFGyUkJeJ8p8Nh4XtZCX3PaEk4U8pMO49tqvMRbgZDZD"
database:
  adapter: 'mysql2' # or 'postgresql' or 'sqlite3'
  host: 'localhost'
  database: 'thebridge_development'
  username: 'root'
  password: ''
