page_token: "EAAPsXXTUUuwBAAgGwy4sUwvc5IbZCpUZC1dRTMwwi8zGsfB6dHqe3AoZCjIKjUbSGsWtchVOXKrsp42aWShUyjSPI9CSRXlg2LEGHaFh5rnbMAQRzrdjY8rNDC3nTxOy4EYpEDPvOeO9kmP4ZAfmoXfoeulCv6C4PQacFhffZAwZDZD"
database:
  adapter: 'mysql2' # or 'postgresql' or 'sqlite3'
  host: 'localhost'
  database: 'thebridge_development'
  username: 'root'
  password: ''
